# Generated by Django 5.0.6 on 2024-06-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activosmodel',
            name='estado',
            field=models.CharField(choices=[('OPERATIVO', 'OPERATIVO'), ('Mantenimiento', 'Mantenimiento'), ('OPERATIVO', 'OPERATIVO')], max_length=33),
        ),
        migrations.AddField(
            model_name='laboratoriosmodel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='laboratories/'),
        ),
        migrations.DeleteModel(
            name='EstadosModel',
        ),
    ]
