# Generated by Django 5.0.6 on 2024-06-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_activosmodel_estado_laboratoriosmodel_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activosmodel',
            name='estado',
            field=models.CharField(choices=[('OPERATIVO', 'OPERATIVO'), ('Mantenimiento', 'Mantenimiento'), ('BUEN ESTADO', 'BUEN ESTADO')], max_length=33),
        ),
    ]
