# Generated by Django 5.0.6 on 2024-06-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_activosmodel_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activosmodel',
            name='codigo_activo',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='activosmodel',
            name='estado',
            field=models.CharField(choices=[('OPERATIVO', 'OPERATIVO'), ('Mantenimiento', 'Mantenimiento'), ('BUEN ESTADO', 'BUEN ESTADO')], max_length=15),
        ),
        migrations.AlterField(
            model_name='activosmodel',
            name='estado_uso',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('VIEJO', 'Viejo')], max_length=6),
        ),
        migrations.AlterField(
            model_name='laboratoriosmodel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='laboratorios/'),
        ),
        migrations.AlterField(
            model_name='marcasmodel',
            name='nombre_marca',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoactivosmodel',
            name='nombre_tipo',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
